# Generated by Django 2.1.5 on 2019-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_comment_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
