# Generated by Django 2.1.5 on 2019-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190730_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
