# Generated by Django 2.1.5 on 2019-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190807_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='viewNumber',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme'),
        ),
    ]
