# Generated by Django 2.1.5 on 2019-08-14 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0011_auto_20190807_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfCOmment',
            fields=[
                ('commentOfComment_content', models.CharField(max_length=100, verbose_name='Yorum')),
                ('commentOfComment_date', models.DateTimeField(auto_now_add=True)),
                ('commentOfComment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOfComment', to='article.Comment', verbose_name='Yorumun yorumu')),
            ],
            options={
                'ordering': ['-commentOfComment_date'],
            },
        ),
    ]
