# Generated by Django 2.1.5 on 2019-08-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20190816_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentofcomment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Makale'),
        ),
    ]
