# Generated by Django 2.1.5 on 2019-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_commentofcomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kategori',
            field=models.TextField(choices=[('Yazılım', 'Yazılım'), ('Şiir', 'Şiir'), ('Fikir', 'Fikir'), ('Teknoloji', 'Teknoloji'), ('Öykü', 'Öykü'), ('Bilim', 'Bilim'), ('Eğitim', 'Eğitim')], default='Yok', verbose_name='Kategori'),
        ),
    ]
