# Generated by Django 2.1.5 on 2019-10-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20190930_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofcomment',
            name='commentOfComment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
