# Generated by Django 2.1.5 on 2019-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isTeacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekle'),
        ),
    ]
